name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Fetch origin/master
      run: |
        git fetch --depth=1 origin +refs/heads/${{github.base_ref}}:refs/remotes/origin/${{github.base_ref}}
        git fetch --depth=1 origin +refs/heads/${{github.head_ref}}:refs/remotes/origin/${{github.head_ref}}

    - name: nbconvert README
      uses: runsascoded/nbconvert@v1.1

    - name: Build Docker container for testing
      run: docker build -f Dockerfile.test -t ur-test .

    - name: Run tests
      run: docker run -v $PWD:/ur ur-test
