name: Refresh .md's
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        submodules: true

    - name: nbconvert README
      uses: runsascoded/nbconvert@master
      with:
        args: -x -f -d .,pandas

    - name: install tree
      run: sudo apt-get install -y tree
    - name: inspect examples dir
      run: tree -pug examples

    - name: Build Docker container for testing
      run: docker build -f Dockerfile.test -t runsascoded/ur-test .

    - name: Run tests
      run: docker run runsascoded/ur-test
