name: Refresh .md's
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: nbconvert README
      uses: runsascoded/nbconvert@master
      with:
        args: -x -f -d .,pandas

    # - name: Build Docker container for testing
    #   run: docker build -f Dockerfile.test -t runsascoded/ur-test .

    - name: Run tests
      run: docker run runsascoded/ur-test
