# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      ref: ${{ github.head_ref }}
    - name: Fetch origin/master
      run: |
        git fetch --depth=1 origin +refs/heads/${{github.base_ref}}:refs/remotes/origin/${{github.base_ref}}
        git fetch --depth=1 origin +refs/heads/${{github.head_ref}}:refs/remotes/origin/${{github.head_ref}}
    - name: nbconvert README
      uses: ./.github/actions/convert
      id: convert
      with:
        args: -f -r origin/${{github.base_ref}} -b ${{github.head_ref}} --token ${{secrets.TOKEN}} --repository ${{github.repository}} README.ipynb

    # Runs a single command using the runners shell
    - name: Build Docker container for testing
      run: docker build -f Dockerfile.test -t ur-test .

    - name: Run tests
      run: docker run -v $PWD:/ur ur-test
